const prefix = 'wikimovie';

export const commonActionTypes = {  
  LOAD_GENRES_REQUEST: `${prefix}/LOAD_GENRES_REQUEST`,
  LOAD_GENRES_SUCCESS: `${prefix}/LOAD_GENRES_SUCCESS`,
  LOAD_GENRES_FAILURE: `${prefix}/LOAD_GENRES_FAILURE`,

  LOAD_POPULAR_MOVIES_REQUEST: `${prefix}/LOAD_POPULAR_MOVIES_REQUEST`,
  LOAD_POPULAR_MOVIES_SUCCESS: `${prefix}/LOAD_POPULAR_MOVIES_SUCCESS`,
  LOAD_POPULAR_MOVIES_FAILURE: `${prefix}/LOAD_POPULAR_MOVIES_FAILURE`,

  SEARCH_MOVIES_REQUEST: `${prefix}/SEARCH_MOVIES_REQUEST`,
  SEARCH_MOVIES_SUCCESS: `${prefix}/SEARCH_MOVIES_SUCCESS`,
  SEARCH_MOVIES_FAILURE: `${prefix}/SEARCH_MOVIES_FAILURE`,

  LOAD_MOVIE_DETAILS_REQUEST: `${prefix}/LOAD_MOVIE_DETAILS_REQUEST`,
  LOAD_MOVIE_DETAILS_SUCCESS: `${prefix}/LOAD_MOVIE_DETAILS_SUCCESS`,
  LOAD_MOVIE_DETAILS_FAILURE: `${prefix}/LOAD_MOVIE_DETAILS_FAILURE`,
};